name: riot_games
description: A new Flutter package project.
version: 0.0.1
author: Andrew Ackerman <andrew.ackie@gmail.com>
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: 0.12.0+2
  equatable: 0.6.1

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
  mockito: ^4.1.1